package org.firstinspires.ftc.teamcode.robot.subsystems;

import com.qualcomm.robotcore.hardware.*;
import org.firstinspires.ftc.teamcode.core.lib.interfaces.Subsystem;
import org.firstinspires.ftc.teamcode.robot.Constants;

/** Subsystem for controlling a continuous rotation servo mechanism. Generated by FGCLib Studio. */
public class ContinuousServo implements Subsystem {
  private static ContinuousServo instance;
  private CRServo servo1;
  private CRServo servo2;

  private CRServo servo3;
  private CRServo servo4;

  /** Private constructor for singleton pattern */
  protected ContinuousServo() {}

  /** Returns the singleton instance of the subsystem */
  public static synchronized ContinuousServo getInstance() {
    if (instance == null) {
      instance = new ContinuousServo();
    }
    return instance;
  }

  /** Rotates the continuous servo clockwise. */
  public void rotateClockwise() {
    servo1.setPower(Constants.ContinuousServo.CLOCKWISE_SPEED);
    servo2.setPower(Constants.ContinuousServo.CLOCKWISE_SPEED);
    servo3.setPower(Constants.ContinuousServo.CLOCKWISE_SPEED);
    servo4.setPower(Constants.ContinuousServo.CLOCKWISE_SPEED);
  }

  /** Rotates the continuous servo counter-clockwise. */
  public void rotateCounterClockwise() {
    servo1.setPower(Constants.ContinuousServo.COUNTER_CLOCKWISE_SPEED);
    servo2.setPower(Constants.ContinuousServo.COUNTER_CLOCKWISE_SPEED);
    servo3.setPower(Constants.ContinuousServo.COUNTER_CLOCKWISE_SPEED);
    servo4.setPower(Constants.ContinuousServo.COUNTER_CLOCKWISE_SPEED);
  }

  /** Stops the mechanism movement. */
  public void stopRotation() {
    servo1.setPower(0);
    servo2.setPower(0);
    servo3.setPower(0);
    servo4.setPower(0);
  }

  /** Initializes hardware and PID controllers */
  @Override
  public void initialize(HardwareMap hardwareMap) {
    servo1 = hardwareMap.get(CRServo.class, Constants.ContinuousServo.SERVO_1_NAME);
    servo1.setDirection(
        Constants.ContinuousServo.IS_INVERTED1
            ? CRServo.Direction.REVERSE
            : CRServo.Direction.FORWARD);
    servo2 = hardwareMap.get(CRServo.class, Constants.ContinuousServo.SERVO_2_NAME);
    servo2.setDirection(
        Constants.ContinuousServo.IS_INVERTED2
            ? CRServo.Direction.REVERSE
            : CRServo.Direction.FORWARD);

    servo3 = hardwareMap.get(CRServo.class, Constants.ContinuousServo.SERVO_3_NAME);
    servo3.setDirection(
        Constants.ContinuousServo.IS_INVERTED3
            ? CRServo.Direction.REVERSE
            : CRServo.Direction.FORWARD);

    servo4 = hardwareMap.get(CRServo.class, Constants.ContinuousServo.SERVO_4_NAME);
    servo4.setDirection(
        Constants.ContinuousServo.IS_INVERTED4
            ? CRServo.Direction.REVERSE
            : CRServo.Direction.FORWARD);
  }

  /** Main control loop, handled by GamepadManager */
  @Override
  public void execute() {
    // Empty execution logic for Claw
  }

  /** Reset state when OpMode starts */
  @Override
  public void start() {
    stopRotation();
  }

  /** Ensures safety when OpMode stops */
  @Override
  public void stop() {
    stopRotation();
  }
}
