package org.firstinspires.ftc.teamcode.robot.subsystems;

import com.qualcomm.robotcore.hardware.*;
import org.firstinspires.ftc.teamcode.core.lib.interfaces.Subsystem;
import org.firstinspires.ftc.teamcode.robot.Constants;

/**
 * Subsystem for controlling an intake mechanism to collect game elements. Generated by FGCLib
 * Studio.
 */
public class Conveyor implements Subsystem {
  private static Conveyor instance;
  private DcMotor motor;

  /** Private constructor for singleton pattern */
  protected Conveyor() {}

  /** Returns the singleton instance of the subsystem */
  public static synchronized Conveyor getInstance() {
    if (instance == null) {
      instance = new Conveyor();
    }
    return instance;
  }

  /** Sets manual power to the mechanism motors. */
  public void setPower(double power) {
    motor.setPower(power);
  }

  /** Initializes hardware and PID controllers */
  @Override
  public void initialize(HardwareMap hardwareMap) {
    motor = hardwareMap.get(DcMotor.class, Constants.Conveyor.MOTOR_NAME);
    motor.setDirection(
        Constants.Conveyor.IS_INVERTED ? DcMotor.Direction.REVERSE : DcMotor.Direction.FORWARD);
    motor.setMode(DcMotor.RunMode.RUN_WITHOUT_ENCODER);
  }

  /** Main control loop, handled by GamepadManager */
  @Override
  public void execute() {}

  /** Reset state when OpMode starts */
  @Override
  public void start() {}

  /** Ensures safety when OpMode stops */
  @Override
  public void stop() {
    setPower(0);
  }
}
