package org.firstinspires.ftc.teamcode.robot.subsystems;

import com.qualcomm.robotcore.hardware.*;
import org.firstinspires.ftc.teamcode.core.lib.interfaces.Subsystem;
import org.firstinspires.ftc.teamcode.robot.Constants;

/**
 * Subsystem for controlling an intake mechanism to collect game elements. Generated by FGCLib
 * Studio.
 */
public class Intake implements Subsystem {
  private static Intake instance;
  private DcMotor motor1;

  /** Private constructor for singleton pattern */
  protected Intake() {}

  /** Returns the singleton instance of the subsystem */
  public static synchronized Intake getInstance() {
    if (instance == null) {
      instance = new Intake();
    }
    return instance;
  }

  /** Sets manual power to the mechanism motors. */
  public void setPower(double power) {
    motor1.setPower(power);
  }

  /** Stops the mechanism movement. */
  public void stopIntake() {
    setPower(0);
  }

  /** Initializes hardware and PID controllers */
  @Override
  public void initialize(HardwareMap hardwareMap) {
    motor1 = hardwareMap.get(DcMotor.class, Constants.Intake.MOTOR_NAME);
    motor1.setDirection(
        Constants.Intake.IS_INVERTED ? DcMotor.Direction.REVERSE : DcMotor.Direction.FORWARD);
    motor1.setMode(DcMotor.RunMode.RUN_WITHOUT_ENCODER);
  }

  /** Main control loop, handled by GamepadManager */
  @Override
  public void execute() {}

  /** Reset state when OpMode starts */
  @Override
  public void start() {}

  /** Ensures safety when OpMode stops */
  @Override
  public void stop() {
    stopIntake();
  }
}
