package org.firstinspires.ftc.teamcode.robot.subsystems;

import Ori.Coval.Logging.Logger.KoalaLog;
import com.qualcomm.robotcore.hardware.*;
import org.firstinspires.ftc.teamcode.core.lib.interfaces.Subsystem;
import org.firstinspires.ftc.teamcode.core.lib.pid.PIDController;
import org.firstinspires.ftc.teamcode.robot.Constants;

/**
 * Subsystem for controlling a shooter mechanism with PIDF velocity control. Generated by FGCLib
 * Studio.
 */
public class Shooter implements Subsystem {
  private static Shooter instance;

  private DcMotorEx motorLeft;
  private DcMotorEx motorRight;

  private PIDController pidController;
  private boolean shooterIsActive = false;

  /** Private constructor for singleton pattern */
  protected Shooter() {}

  /** Returns the singleton instance of the subsystem */
  public static synchronized Shooter getInstance() {
    if (instance == null) {
      instance = new Shooter();
    }
    return instance;
  }

  /** Spins up the shooter motor to the target velocity. */
  public void spinUp() {
    shooterIsActive = true;
  }

  /** Stops the mechanism movement. */
  public void stopShooter() {
    shooterIsActive = false;
  }

  /** Sets manual power to the mechanism motors. */
  public void runMotorPower(double power) {
    shooterIsActive = false;
    motorLeft.setPower(power);
    motorRight.setPower(power);
  }

  /** Updates the PID controller coefficients from Constants. */
  public void updatePID() {
    pidController.setKP(Constants.Shooter.PID.kP);
    pidController.setKI(Constants.Shooter.PID.kI);
    pidController.setKD(Constants.Shooter.PID.kD);
    pidController.setKF(Constants.Shooter.PID.kF);
  }

  /** Initializes hardware and PID controllers */
  @Override
  public void initialize(HardwareMap hardwareMap) {
    motorLeft = hardwareMap.get(DcMotorEx.class, Constants.Shooter.MOTOR_LEFT_NAME);
    motorLeft.setDirection(
        Constants.Shooter.IS_INVERTED_LEFT ? DcMotor.Direction.REVERSE : DcMotor.Direction.FORWARD);
    motorLeft.setMode(DcMotor.RunMode.RUN_WITHOUT_ENCODER);
    motorLeft.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.FLOAT);

    motorRight = hardwareMap.get(DcMotorEx.class, Constants.Shooter.MOTOR_RIGHT_NAME);
    motorRight.setDirection(
        Constants.Shooter.IS_INVERTED_RIGHT
            ? DcMotor.Direction.REVERSE
            : DcMotor.Direction.FORWARD);
    motorRight.setMode(DcMotor.RunMode.RUN_WITHOUT_ENCODER);
    motorRight.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.FLOAT);

    pidController =
        new PIDController(
            Constants.Shooter.PID.kP,
            Constants.Shooter.PID.kI,
            Constants.Shooter.PID.kD,
            Constants.Shooter.PID.kF);
    pidController.setTolerance(Constants.Shooter.TOLERANCE);
  }

  /** Main control loop, handled by GamepadManager */
  @Override
  public void execute() {
    if (shooterIsActive) {
      double currentVelocity = motorLeft.getVelocity();
      double power = pidController.calculate(Constants.Shooter.TARGET_VELOCITY, currentVelocity);

      motorLeft.setPower(power);
      motorRight.setPower(power);
    }

    KoalaLog.log("Current Velocity Left", getcurrentVelocityLeft(), true);
    KoalaLog.log("Current Velocity Right", getcurrentVelocityRight(), true);
  }

  /** Reset state when OpMode starts */
  @Override
  public void start() {
    shooterIsActive = false;
    stop();
  }

  /** Ensures safety when OpMode stops */
  @Override
  public void stop() {
    shooterIsActive = false;
    motorLeft.setPower(0);
    motorRight.setPower(0);
  }

  public double getcurrentVelocityLeft() {
    return (motorLeft.getVelocity() / 28) * 60;
  }

  public double getcurrentVelocityRight() {
    return (motorRight.getVelocity() / 28) * 60;
  }
}
