package org.firstinspires.ftc.teamcode.robot.subsystems;

import com.acmerobotics.dashboard.FtcDashboard;
import com.acmerobotics.dashboard.telemetry.TelemetryPacket;
import com.qualcomm.robotcore.hardware.*;

import org.firstinspires.ftc.teamcode.core.lib.interfaces.Subsystem;
import org.firstinspires.ftc.teamcode.core.lib.pid.PIDController;
import org.firstinspires.ftc.teamcode.robot.Constants;

import Ori.Coval.Logging.Logger.KoalaLog;

/**
 * Subsystem for controlling a shooter mechanism with PIDF velocity control.
 * Generated by FGCLib Studio.
 */
public class Shooter implements Subsystem {
  private static Shooter instance;

  private DcMotorEx motorLeft;
  private DcMotorEx motorRight;

  private PIDController pidController;
  private boolean shooterIsActive = false;

  /** Private constructor for singleton pattern */
  protected Shooter() {}

  /** Returns the singleton instance of the subsystem */
  public static synchronized Shooter getInstance() {
    if (instance == null) {
      instance = new Shooter();
    }
    return instance;
  }

  /** Spins up the shooter motor to the target velocity. */
  public void spinUp() {
    shooterIsActive = true;
  }

  /** Sets manual power to the mechanism motors. */
  public void runMotorPower(double power) {
    shooterIsActive = false;
    motorLeft.setPower(power);
    motorRight.setPower(power);
  }

  /** Updates the PID controller coefficients from Constants. */
  public void updatePID() {
    pidController.setKP(Constants.Shooter.PID.kP);
    pidController.setKI(Constants.Shooter.PID.kI);
    pidController.setKD(Constants.Shooter.PID.kD);
    pidController.setKF(Constants.Shooter.PID.kF);
  }

  /** Initializes hardware and PID controllers */
  @Override
  public void initialize(HardwareMap hardwareMap) {
    motorLeft = hardwareMap.get(DcMotorEx.class, Constants.Shooter.MOTOR_LEFT_NAME);
    motorLeft.setDirection(
            Constants.Shooter.IS_INVERTED_LEFT ? DcMotor.Direction.REVERSE : DcMotor.Direction.FORWARD);
    motorLeft.setMode(DcMotor.RunMode.RUN_WITHOUT_ENCODER);
    motorLeft.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.FLOAT);

    motorRight = hardwareMap.get(DcMotorEx.class, Constants.Shooter.MOTOR_RIGHT_NAME);
    motorRight.setDirection(
            Constants.Shooter.IS_INVERTED_RIGHT
                    ? DcMotor.Direction.REVERSE
                    : DcMotor.Direction.FORWARD);
    motorRight.setMode(DcMotor.RunMode.RUN_WITHOUT_ENCODER);
    motorRight.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.FLOAT);

    pidController =
            new PIDController(
                    Constants.Shooter.PID.kP,
                    Constants.Shooter.PID.kI,
                    Constants.Shooter.PID.kD,
                    Constants.Shooter.PID.kF);
    pidController.setTolerance(Constants.Shooter.TOLERANCE);
  }

  /** Main control loop, handled by GamepadManager */
  @Override
  public void execute() {
    if (Constants.tuningMode) {
      updatePID();
    }

    double currentVelocityLeft = motorLeft.getVelocity();
    double currentVelocityRight = motorRight.getVelocity();

    if (shooterIsActive) {
      double power = pidController.calculate(Constants.Shooter.TARGET_VELOCITY, currentVelocityLeft);

      motorLeft.setPower(power);
      motorRight.setPower(power);
    }

    if (Constants.tuningMode) {
      TelemetryPacket packet = new TelemetryPacket();
      packet.put("Shooter Target Velocity", Constants.Shooter.TARGET_VELOCITY);
      packet.put("Shooter Current Velocity Left", currentVelocityLeft);
      packet.put("Shooter Current Velocity Right", currentVelocityRight);
      packet.put("Shooter RPM Left", getcurrentVelocityLeft());
      packet.put("Shooter RPM Right", getcurrentVelocityRight());
      packet.put("Shooter Error", Constants.Shooter.TARGET_VELOCITY - currentVelocityLeft);
      packet.put("Shooter Power", motorLeft.getPower());
      FtcDashboard.getInstance().sendTelemetryPacket(packet);
    }

    // Logging no KoalaLog
    KoalaLog.log("Current Velocity Left", getcurrentVelocityLeft(), true);
    KoalaLog.log("Current Velocity Right", getcurrentVelocityRight(), true);
  }

  /** Reset state when OpMode starts */
  @Override
  public void start() {
    shooterIsActive = false;
    stop();
  }

  /** Ensures safety when OpMode stops */
  @Override
  public void stop() {
    shooterIsActive = false;
    motorLeft.setPower(0);
    motorRight.setPower(0);
  }

  public double getcurrentVelocityLeft() {
    return (motorLeft.getVelocity() / 28.0) * 60.0;
  }

  public double getcurrentVelocityRight() {
    return (motorRight.getVelocity() / 28.0) * 60.0;
  }

  public boolean readyToShoot() {
    return Math.abs(getcurrentVelocityRight()) >= Constants.Shooter.READY_TO_SHOOT_VELOCITY;
  }

  public boolean almostReadyToShoot() {
    return Math.abs(getcurrentVelocityRight()) >= Constants.Shooter.ALMOST_READY_TO_SHOOT_VELOCITY;
  }
}