package org.firstinspires.ftc.teamcode.robot.subsystems;

import Ori.Coval.Logging.Logger.KoalaLog;
import com.qualcomm.robotcore.hardware.*;
import org.firstinspires.ftc.teamcode.core.lib.interfaces.Subsystem;
import org.firstinspires.ftc.teamcode.core.lib.pid.PIDController;
import org.firstinspires.ftc.teamcode.robot.Constants;

/**
 * Subsystem for controlling a shooter mechanism with PIDF velocity control. Generated by FGCLib
 * Studio.
 */
public class Shooter implements Subsystem {
  private static Shooter instance;
  private DcMotorEx motor1;
  private DcMotorEx motor2;
  private PIDController pidController;
  private boolean shooterIsActive = false;

  /** Private constructor for singleton pattern */
  protected Shooter() {}

  /** Returns the singleton instance of the subsystem */
  public static synchronized Shooter getInstance() {
    if (instance == null) {
      instance = new Shooter();
    }
    return instance;
  }

  /** Spins up the shooter motor to the target velocity. */
  public void spinUp() {
    shooterIsActive = true;
  }

  /** Stops the mechanism movement. */
  public void stopShooter() {
    shooterIsActive = false;
  }

  /** Sets manual power to the mechanism motors. */
  public void runMotorPower(double power) {
    shooterIsActive = false;
    motor1.setPower(power);
    motor2.setPower(power);
  }

  /** Updates the PID controller coefficients from Constants. */
  public void updatePID() {
    pidController.setKP(Constants.Shooter.PID.kP);
    pidController.setKI(Constants.Shooter.PID.kI);
    pidController.setKD(Constants.Shooter.PID.kD);
    pidController.setKF(Constants.Shooter.PID.kF);
  }

  /** Initializes hardware and PID controllers */
  @Override
  public void initialize(HardwareMap hardwareMap) {
    motor1 = hardwareMap.get(DcMotorEx.class, Constants.Shooter.MOTOR_1_NAME);
    motor1.setDirection(
        Constants.Shooter.IS_INVERTED1 ? DcMotor.Direction.REVERSE : DcMotor.Direction.FORWARD);
    motor1.setMode(DcMotor.RunMode.RUN_WITHOUT_ENCODER);
    motor1.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.FLOAT);
    motor2 = hardwareMap.get(DcMotorEx.class, Constants.Shooter.MOTOR_2_NAME);
    motor2.setDirection(
        Constants.Shooter.IS_INVERTED2 ? DcMotor.Direction.REVERSE : DcMotor.Direction.FORWARD);
    motor2.setMode(DcMotor.RunMode.RUN_WITHOUT_ENCODER);
    motor2.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.FLOAT);

    pidController =
        new PIDController(
            Constants.Shooter.PID.kP,
            Constants.Shooter.PID.kI,
            Constants.Shooter.PID.kD,
            Constants.Shooter.PID.kF);
    pidController.setTolerance(20.0);
  }

  /** Main control loop, handled by GamepadManager */
  @Override
  public void execute() {
    if (shooterIsActive) {
      double currentVelocity = motor1.getVelocity();
      double power = pidController.calculate(Constants.Shooter.TARGET_VELOCITY, currentVelocity);
      motor1.setPower(power);
      if (motor2 != null) motor2.setPower(power);
    }

    KoalaLog.log("Current Velocity Left", getcurrentVelocityLeft(), true);
    KoalaLog.log("Current Velocity Right", getcurrentVelocityRight(), true);
  }

  /** Reset state when OpMode starts */
  @Override
  public void start() {
    shooterIsActive = false;
    stop();
  }

  /** Ensures safety when OpMode stops */
  @Override
  public void stop() {
    shooterIsActive = false;
    motor1.setPower(0);
    if (motor2 != null) motor2.setPower(0);
  }

  public double getcurrentVelocityLeft() {
    return (motor1.getVelocity() / 28) * 60;
  }

  public double getcurrentVelocityRight() {
    return (motor2.getVelocity() / 28) * 60;
  }
}
