package org.firstinspires.ftc.teamcode.robot;

import com.acmerobotics.dashboard.config.Config;

/** Centralized robot constants. Generated by FGCLib Studio. */
@Config
public class Constants {
  public static class DrivetrainBuilderConstants {
    public static final String MOTOR_RIGHT_NAME = "motor_right";
    public static final String MOTOR_LEFT_NAME = "motor_left";
    public static final boolean IS_MOTOR_RIGHT_INVERTED = false;
    public static final boolean IS_MOTOR_LEFT_INVERTED = true;
  }

  @Config
  public static class Shooter {
    public static final String MOTOR_1_NAME = "motor1";
    public static final String MOTOR_2_NAME = "motor2";
    public static boolean IS_INVERTED1 = false;
    public static boolean IS_INVERTED2 = true;

    /** The target speed the motor will try to achieve, in ticks per second. */
    public static int TARGET_VELOCITY = 4000;

    /** PID Controller tuning coefficients. */
    public static class PID {
      /** (Proportional) Reacts to the speed difference. */
      public static double kP = 0.5;

      /** (Integral) Corrects small, persistent speed errors. */
      public static double kI = 0;

      /** (Derivative) Prevents speed oscillation. */
      public static double kD = 0;

      /**
       * (Feedforward) The base force applied to reach the target speed, even before there is an
       * error.
       */
      public static double kF = 0.05;
    }
  }

  public static class Intake {
    public static final String MOTOR_1_NAME = "motor4";
    public static final boolean IS_INVERTED1 = true;

    /** The default speed to turn on the intake (0.0 to 1.0). */
    public static final double INTAKE_SPEED = 1.0;
  }

  public static class Conveyor {
    public static final String MOTOR_1_NAME = "motor3";
    public static final boolean IS_INVERTED1 = false;

    /** The default speed to turn on the intake (0.0 to 1.0). */
    public static final double INTAKE_SPEED = 1.0;
  }

  public static class Door {
    public static final String SERVO_1_NAME = "Door_servo_1";

    /** Enum representing preset servo positions. */
    public enum Position {
      OPEN("open"),
      CLOSED("closed"),
      ;
      private final String id;

      Position(String id) {
        this.id = id;
      }

      public String getId() {
        return id;
      }
    }

    /** Preset position: Open */
    public static final double OPEN_POSITION_1 = 1.0;

    /** Preset position: Closed */
    public static final double CLOSED_POSITION_1 = 0.5;
  }

  public static class Storage {
    public static final String MOTOR_1_NAME = "storage_motor_left";
    public static final String MOTOR_2_NAME = "storage_motor_right";
    public static final boolean IS_INVERTED1 = false;
    public static final boolean IS_INVERTED2 = false;

    /** Storage position at the lowest point, in encoder ticks. */
    public static final int LOW_POSITION = 100;

    /** Storage position at the highest point, in encoder ticks. */
    public static final int HIGH_POSITION = 2000;

    /** PID Controller tuning coefficients. */
    public static class PID {
      /**
       * (Proportional) Reacts to the current error. Increase for a faster response, but beware of
       * oscillation.
       */
      public static double kP = 0.05;

      /** (Integral) Eliminates residual error by accumulating it over time. Use small values. */
      public static double kI = 0;

      /** (Derivative) Prevents speed oscillation. */
      public static double kD = 0;

      /** Feedforward coefficient (kF). */
      public static double kF = 0;
    }
  }

  public static class ContinuousServo {
    public static final String SERVO_1_NAME = "servo_1";
    public static final String SERVO_2_NAME = "servo_2";
    public static final String SERVO_3_NAME = "servo_3";
    public static final String SERVO_4_NAME = "servo_4";
    public static final boolean IS_INVERTED1 = false;
    public static final boolean IS_INVERTED2 = false;
    public static final boolean IS_INVERTED3 = true;
    public static final boolean IS_INVERTED4 = true;

    /** Speed for clockwise rotation (0 to 1). */
    public static final int CLOCKWISE_SPEED = 1;

    /** Speed for counter-clockwise rotation (-1 to 0). */
    public static final int COUNTER_CLOCKWISE_SPEED = -1;
  }
}
