package org.firstinspires.ftc.teamcode.robot;

import com.acmerobotics.dashboard.config.Config;

/** Centralized robot constants. Generated by FGCLib Studio. */
@Config
public class Constants {
  public static boolean tuningMode = true;

  public static class DrivetrainBuilderConstants {
    public static final String MOTOR_RIGHT_NAME = "drivetrain_motor_right";
    public static final String MOTOR_LEFT_NAME = "drivetrain_motor_left";
    public static final boolean IS_MOTOR_RIGHT_INVERTED = false;
    public static final boolean IS_MOTOR_LEFT_INVERTED = true;
  }

  @Config
  public static class Shooter {
    public static final String MOTOR_LEFT_NAME = "shooter_motor_left";
    public static final String MOTOR_RIGHT_NAME = "shooter_motor_right";
    public static final boolean IS_INVERTED_LEFT = false;
    public static final boolean IS_INVERTED_RIGHT = true;

    public static final double TOLERANCE = 20;

    /** The target speed the motor will try to achieve, in ticks per second. */
    public static int TARGET_VELOCITY = 4500;
    public static int READY_TO_SHOOT_VELOCITY = 4000;

    public static int ALMOST_READY_TO_SHOOT_VELOCITY = 3000;

    /** PID Controller tuning coefficients. */
    public static class PID {
      /** (Proportional) Reacts to the speed difference. */
      public static double kP = 0.5;

      /** (Integral) Corrects small, persistent speed errors. */
      public static double kI = 0;

      /** (Derivative) Prevents speed oscillation. */
      public static double kD = 0;

      /**
       * (Feedforward) The base force applied to reach the target speed, even before there is an
       * error.
       */
      public static double kF = 0.05;
    }
  }

  public static class Intake {
    public static final String MOTOR_NAME = "intake_motor";
    public static final boolean IS_INVERTED = true;

    /** The default speed to turn on the intake (0.0 to 1.0). */
    public static final double INTAKE_SPEED = 1.0;
  }

  public static class Conveyor {
    public static final String MOTOR_NAME = "conveyor_motor";
    public static final boolean IS_INVERTED = false;

    /** The default speed to turn on the conveyor (0.0 to 1.0). */
    public static final double CONVEYOR_SPEED = 1.0;
  }

  public static class Storage {
    public static final String MOTOR_NAME = "storage_motor";
    public static final boolean IS_INVERTED = false;

    /** Storage position at the lowest point, in encoder ticks. */
    public static final int LOW_POSITION = 100;

    /** Storage position at the highest point, in encoder ticks. */
    public static final int HIGH_POSITION = 2000;

    /** PID Controller tuning coefficients. */
    @Config
    public static class PID {
      /**
       * (Proportional) Reacts to the current error. Increase for a faster response, but beware of
       * oscillation.
       */
      public static double kP = 0.05;

      /** (Integral) Eliminates residual error by accumulating it over time. Use small values. */
      public static double kI = 0;

      /** (Derivative) Prevents speed oscillation. */
      public static double kD = 0;

      /** Feedforward coefficient (kF). */
      public static double kF = 0;
    }
  }
}
