package org.firstinspires.ftc.teamcode.robot;

import com.acmerobotics.dashboard.config.Config;

/** Centralized robot constants. Generated by FGCLib Studio. */
@Config
public class Constants {
  /** Example subsystem constants. You can delete this class if you don't use SubsystemExample. */
  public static class SubsystemExample {
    public static final String MOTOR_LEFT = "subsystemExample_motorLeft";
    public static final String MOTOR_RIGHT = "subsystemExample_motorRight";
    public static final String LIMIT_LEFT = "subsystemExample_limitLeft";
    public static final String LIMIT_RIGHT = "subsystemExample_limitRight";

    /** PID tuning constants for the example subsystem. */
    public static class PID {
      public static final double kP = 1.8;
      public static final double kI = 0.0;
      public static final double kD = 0.031;
      public static final double kF = 0.1;
    }
  }

<<<<<<< Updated upstream
  /** Configuration values for the example subsystem. */
  public static class SubsystemExample {
    public static final String MOTOR_LEFT = "subsystemExample_motorLeft";
    public static final String MOTOR_RIGHT = "subsystemExample_motorRight";
    public static final String LIMIT_LEFT = "subsystemExample_limitLeft";
    public static final String LIMIT_RIGHT = "subsystemExample_limitRight";

    /** PID tuning constants. */
    public static class PID {
      public static final double kP = 1.8;
      public static final double kI = 0.0;
      public static final double kD = 0.031;
      public static final double kF = 0.1;
    }
=======
  public static class DrivetrainBuilderConstants {
    public static final String MOTOR_RIGHT_NAME = "motor_right";
    public static final String MOTOR_LEFT_NAME = "motor_left";
    public static final boolean IS_MOTOR_RIGHT_INVERTED = false;
    public static final boolean IS_MOTOR_LEFT_INVERTED = true;
  }

  @Config
  public static class Shooter {
    public static final String MOTOR_1_NAME = "motor1";
    public static final String MOTOR_2_NAME = "motor2";
    public static boolean IS_INVERTED1 = false;
    public static boolean IS_INVERTED2 = true;

    /** The target speed the motor will try to achieve, in ticks per second. */
    public static int TARGET_VELOCITY = 4000;

    /** PID Controller tuning coefficients. */
    public static class PID {
      /** (Proportional) Reacts to the speed difference. */
      public static double kP = 0.5;

      /** (Integral) Corrects small, persistent speed errors. */
      public static double kI = 0;

      /** (Derivative) Prevents speed oscillation. */
      public static double kD = 0;

      /**
       * (Feedforward) The base force applied to reach the target speed, even before there is an
       * error.
       */
      public static double kF = 0.05;
    }
  }

  public static class Intake {
    public static final String MOTOR_1_NAME = "motor4";
    public static final boolean IS_INVERTED1 = true;

    /** The default speed to turn on the intake (0.0 to 1.0). */
    public static final double INTAKE_SPEED = 1.0;
  }

  public static class Conveyor {
    public static final String MOTOR_1_NAME = "motor3";
    public static final boolean IS_INVERTED1 = false;

    /** The default speed to turn on the intake (0.0 to 1.0). */
    public static final double INTAKE_SPEED = 1.0;
>>>>>>> Stashed changes
  }
}
